### PR TITLE
Use tuple inference for closures

### LINKED ISSUE #4: Always make the "upvar types" a tuple of the actual upvar types (Parent issue#53488)
**Updated by nikomatsakis with current status:**

In https://github.com/rust-lang/rust/pull/69968, @eddyb landed the "first step" here of introducing a tuple into the upvar types. However, in current rustc, we create that tuple "eagerly", as soon as we create the closure type:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_typeck/check/closure.rs#L90-L103

The next step is to move that tuple creation "late", so that it occurs during the "upvar analysis" code, so somewhere around here:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_typeck/check/upvar.rs#L194-L202

The problem with *this* is that the current accessor, [`ClosureSubsts::upvar_tys`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.ClosureSubsts.html#method.upvar_tys), assumes that the upvar types are a tuple with known arity. Thus any calls to `upvar_tys` that occur before the upvar analysis code runs will ICE. 

Last time, we added an accessor `upvar_tuple_ty` that returned the *tuple itself* (or an unbound type variable), since it turned out that many of the calls to `upvar_tys` could be replaced by a call that operated on the tuple. Most notably, in the trait system, for example here:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_trait_selection/traits/select.rs#L2239-L2242

We changed this to yield the tuple always. The problem with *that* was that it was effecting the error messages, because the tuple was being introduced into the "backtrace" and we somehow never got things *quiite* right to remove it.

I still think that is perhaps the right approach, but there is an alternative we could try: we could get the tuple ty and check whether it's been "resolved" yet (via a call to [`self.infcx.shallow_resolve`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/struct.InferCtxt.html#method.shallow_resolve)). If so, we can put each of its components as we do today, but if not, we can return `Ambiguous`, [as we do here](https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_trait_selection/traits/select.rs#L2249-L2254).

### PR DESCRIPTION
**Pull request by roxelo**
The main motivation behind this change is to allow the compiler to decide the number of captures after capture analysis instead of before capture analysis. T

This is required to support RFC-2229, since the number of captures will not be know before capture analysis.

Closes rust-lang/project-rfc-2229#4

---
This change is [Reviewable](https://reviewable.io/reviews/sexxi-goose/rust/23)

### CODE REVIEW

File: compiler/rustc_middle/src/ty/outlives.rs [hunk 1]
```diff
@@ -89,8 +89,13 @@ fn compute_components(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>, out: &mut SmallVec<[Compo
             }
 
             ty::Closure(_, ref substs) => {
-                for upvar_ty in substs.as_closure().upvar_tys() {
-                    compute_components(tcx, upvar_ty, out);
+                let tupled_ty = substs.as_closure().tupled_upvars_ty();
+                if matches!(tupled_ty.kind(), ty::Tuple(_)) {
```
Comment (arora-aman) [inline compiler/rustc_middle/src/ty/outlives.rs]: This is my bad, this can just be `substs.as_closure().is_valid()`

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 2]
```diff
@@ -1730,11 +1736,31 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
                 tys.iter().map(|k| k.expect_ty()).collect()
             }
 
-            ty::Closure(_, ref substs) => substs.as_closure().upvar_tys().collect(),
+            ty::Closure(_, ref substs) => {
+                let ty = self.infcx.shallow_resolve(substs.as_closure().tupled_upvars_ty());
+                if let ty::Infer(ty::TyVar(_)) = ty.kind() {
```
Comment (arora-aman) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs]: I think you can just do `constituent_types_for_ty(ty)`, but don't think that's the issue rn

File: compiler/rustc_trait_selection/src/traits/select/mod.rs [hunk 3]
```diff
@@ -1730,11 +1736,31 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
+                    substs.as_closure().upvar_tys().collect()
+                }
+            }
 
             ty::Generator(_, ref substs, _) => {
-                let witness = substs.as_generator().witness();
-                substs.as_generator().upvar_tys().chain(iter::once(witness)).collect()
+                let ty = self.infcx.shallow_resolve(substs.as_generator().tupled_upvars_ty());
+                if let ty::Infer(ty::TyVar(_)) = ty.kind() {
+                    // Not yet resolved.
```
Comment (arora-aman) [inline compiler/rustc_trait_selection/src/traits/select/mod.rs]: same as above

File: compiler/rustc_trait_selection/src/opaque_types.rs [hunk 4]
```diff
@@ -716,24 +720,36 @@ where
             ty::Closure(_, ref substs) => {
                 // Skip lifetime parameters of the enclosing item(s)
 
-                for upvar_ty in substs.as_closure().upvar_tys() {
-                    upvar_ty.visit_with(self);
-                }
+                let ty = self.infcx.shallow_resolve(substs.as_closure().tupled_upvars_ty());
+                if let ty::Infer(ty::TyVar(_)) = ty.kind() {
+                    // Not yet resolved.
+                    ty.super_visit_with(self);
```
Comment (arora-aman) [inline compiler/rustc_trait_selection/src/opaque_types.rs:726]: Not imp rn but I'd just call visit_ty, here.

File: compiler/rustc_trait_selection/src/opaque_types.rs [hunk 5]
```diff
@@ -716,24 +720,36 @@ where
...
                 // Skip lifetime parameters of the enclosing item(s)
                 // Also skip the witness type, because that has no free regions.
 
-                for upvar_ty in substs.as_generator().upvar_tys() {
-                    upvar_ty.visit_with(self);
-                }
+                let ty = self.infcx.shallow_resolve(substs.as_generator().tupled_upvars_ty());
+                if let ty::Infer(ty::TyVar(_)) = ty.kind() {
+                    // Not yet resolved.
+                    ty.super_visit_with(self);
```
Comment (arora-aman) [inline compiler/rustc_trait_selection/src/opaque_types.rs:743]: same

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 6]
```diff
@@ -526,10 +526,7 @@ impl<'a, 'tcx> WfPredicates<'a, 'tcx> {
                     // anyway, except via auto trait matching (which
                     // only inspects the upvar types).
                     walker.skip_current_subtree(); // subtree handled below
-                    for upvar_ty in substs.as_closure().upvar_tys() {
-                        // FIXME(eddyb) add the type to `walker` instead of recursing.
-                        self.compute(upvar_ty.into());
-                    }
+                    self.compute(substs.as_closure().tupled_upvars_ty().into());
```
Comment (arora-aman) [inline compiler/rustc_trait_selection/src/traits/wf.rs:529]: It feels like at this point we would've done capture analysis, based on the comments, but not sure.

Also how `ty::Tuple` is dealt with within this code seems to be different than what was done here before this change.

File: compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs [hunk 7]
```diff
@@ -110,7 +110,12 @@ pub fn trivial_dropck_outlives<'tcx>(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>) -> bool {
         // check if *any* of those are trivial.
         ty::Tuple(ref tys) => tys.iter().all(|t| trivial_dropck_outlives(tcx, t.expect_ty())),
         ty::Closure(_, ref substs) => {
-            substs.as_closure().upvar_tys().all(|t| trivial_dropck_outlives(tcx, t))
+            if !substs.as_closure().is_valid() {
```
Comment (arora-aman) [inline compiler/rustc_trait_selection/src/traits/query/dropck_outlives.rs]: This can just be `trivial_dropck_outlives(tcx, substs.as_closure().tupled_upvar_tys())`

File: compiler/rustc_trait_selection/src/traits/wf.rs [hunk 8]
```diff
@@ -526,10 +526,7 @@ impl<'a, 'tcx> WfPredicates<'a, 'tcx> {
                     // anyway, except via auto trait matching (which
                     // only inspects the upvar types).
                     walker.skip_current_subtree(); // subtree handled below
-                    for upvar_ty in substs.as_closure().upvar_tys() {
-                        // FIXME(eddyb) add the type to `walker` instead of recursing.
```
Comment (arora-aman) [inline compiler/rustc_trait_selection/src/traits/wf.rs:596]: leave this comment here

File: compiler/rustc_typeck/src/check/closure.rs [hunk 9]
```diff
@@ -81,19 +81,11 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
-                    // inference phase (`upvar.rs`).
-                    self.infcx.next_ty_var(TypeVariableOrigin {
-                        // FIXME(eddyb) distinguish upvar inference variables from the rest.
-                        kind: TypeVariableOriginKind::ClosureSynthetic,
-                        span: self.tcx.hir().span(var_hir_id),
-                    })
-                })
-            }));
+        let tupled_upvars_ty = self.infcx.next_ty_var(TypeVariableOrigin {
+            // FIXME(eddyb) distinguish upvar inference variables from the rest.
```
Comment (arora-aman) [inline compiler/rustc_typeck/src/check/closure.rs]: I feel like this isn't valid anymore, individual inference variable for each upvar, isn't a thing anymore.

File: compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs [hunk 10]
```diff
@@ -1307,6 +1307,26 @@ impl<'a, 'tcx> InferCtxtExt<'tcx> for InferCtxt<'a, 'tcx> {
         let mut generator = None;
         let mut outer_generator = None;
         let mut next_code = Some(&obligation.cause.code);
+        // By introducing a tuple into the upvar types, the first item in the obligation chain
+        // can be of Tuple type instead of the generator that captured the type. We want to catch for
+        // this case and skip it.
```
Comment (roxelo) [inline compiler/rustc_trait_selection/src/traits/error_reporting/suggestions.rs]: This does the trick for now, but it's probably not what we want to move forward with. The tuple of upvar type should not be the first item in the obligation chain, probably more in the middle. We probably want to change how the obligation chain is created. I haven't figured out where in the code that is done yet though

**Review by ChrisPardy — APPROVED** [review]
